name: Minigame
version: '${project.version}'
main: me.kvlike.minigame.Minigame
api-version: 1.17
commands:
  minigame:
    permission: minigame.player
    permission-message: §cYou don't have permission to use that command!
  mga:
    aliases: minigameadmin, mgadmin
    permission: minigame.admin
    permission-message: §cYou don't have permission to use that command!
permissions:
  minigame.player:
    default: true
  minigame.admin:
    default: op
